services:
  dev:
    image: python:3.9
    # Overrides default command so things don't shut down after the process ends
    command: /bin/sh -c "while sleep 1000; do :; done"
    working_dir: /intake-html-table
    volumes:
      - ../:/intake-html-table
